languageCode = 'en-us'
title = "8amiul's Webpage"
description = "Samiul Islam | 19yo from Bangladesh, who likes tech, minimalism, music, video games & many other shit"
theme = 'mytheme'
baseurl = "https://8amiul.github.io"

[params]
    favAlbum.title = "CASTLEBEAT"
    favAlbum.cover = "/images/music-album.jpg"
    author = "8amiul"


[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"




[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 3
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 4
   [[menus.main]]
    name = 'Images'
    pageRef = '/images'
    weight = 5
   [[menus.main]]
    name = 'Music'
    pageRef = '/music'
    weight = 6
   
  [[menus.main]]
    name = 'Bookmarks'
    pageRef = '/bookmarks'
    weight = 7
